name: deno.land Continuous Deployment

on:
  push:
    tags:
      - '@slack/web-api*'
      - '!@slack/web-api*nextGen*'
      - '!@slack/web-api*Beta*'
      - '!@slack/web-api*beta*'

defaults:
  run:
    shell: bash
    working-directory: packages/web-api

jobs:
  transpile:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2
      with:
        # pull all tags/branches with full history;
        # need that to checkout different branch and push artifacts later
        fetch-depth: 0
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - name: Echo Tag Name
      run: echo "$GITHUB_REF_NAME"
    - name: Inject browser field and add dependencies to package.json
      run: |
        perl -pi.bak -e 's/"tsd": {/"browser":{"os":"os-browserify","path":"path-browserify","querystring":".\/deno-shims\/qs-shim.js"},"tsd": {/g' package.json
        perl -pi.bak -e 's/"axios": /"path-browserify":"1.0.1","os-browserify":"0.3.0","axios": /g' package.json
        perl -pi.bak -e 's/"p-retry":/"zlib":".\/deno-shims\/zlib-shim.js","util":".\/deno-shims\/util-shim.js","p-retry":/g' package.json
    - run: npm install
    - run: npm run build:deno
  
